CAU 1:

DECLARE @TBTHONGKE TABLE(MAPB INT, LUONGTB FLOAT)
INSERT INTO @TBTHONGKE 
SELECT PHG, AVG(LUONG) FROM NHANVIEN GROUP BY PHG
SELECT * FROM @TBTHONGKE
SELECT TENNV,PHG, LUONG, LUONGTB,
TINHTRANG = CASE 
WHEN LUONG > LUONGTB THEN 'KHONG TANG LUONG'
ELSE 'TANG LUONG'
END
FROM NHANVIEN A
INNER JOIN @TBTHONGKE B
ON A.PHG = B.MAPB

DECLARE @TBTHONGKE TABLE(MAPB INT, LUONGTB FLOAT)
INSERT INTO @TBTHONGKE 
SELECT PHG, AVG(LUONG) FROM NHANVIEN GROUP BY PHG
SELECT * FROM @TBTHONGKE
SELECT TENNV,PHG, LUONG, LUONGTB,
TINHTRANG = CASE 
WHEN LUONG > LUONGTB THEN 'TRUONG PHONG'
ELSE 'NHAN VIEN'
END
FROM NHANVIEN A
INNER JOIN @TBTHONGKE B
ON A.PHG = B.MAPB

SELECT TENNV = CASE 
WHEN PHAI = 'Nam' THEN 'Mr. ' + TENNV
WHEN PHAI = N'Nữ' THEN 'Ms. ' + TENNV
ELSE 'khong biet' 
END
FROM NHANVIEN

SELECT TENNV, LUONG,
Thue = CASE
WHEN LUONG between 0 and 25000 THEN LUONG * 0.1
WHEN LUONG between 25000 and 30000 THEN LUONG * 0.12
WHEN LUONG between 30000 and 40000 THEN LUONG * 0.15
WHEN LUONG between 40000 and 50000 THEN LUONG * 0.2
ELSE LUONG * 0.25
END
FROM NHANVIEN

CAU2:

SELECT * FROM NHANVIEN
DECLARE @I INT = 2, @DEM INT;
SET @DEM = (SELECT COUNT(*) FROM NHANVIEN)
WHILE (@I < @DEM)
BEGIN
IF (@I = 4) 
BEGIN 
SET @I = @I + 2;
CONTINUE;
END
SELECT MANV, HONV, TENLOT, TENNV FROM NHANVIEN 
WHERE CAST(MANV AS INT) = @I;
SET @I =@I + 2;
END

CAU 3:

BEGIN TRY 
INSERT PHONGBAN (TENPHG, MAPHG, TRPHG,NG_NHANCHUC)
VALUES('KE HOACH',111,'019','2020-12-12')
PRINT'CHE THANH CONG'
END TRY
BEGIN CATCH
PRINT 'LOI' + CONVERT(VARCHAR, ERROR_NUMBER(),1)
+ '=>' + ERROR_MESSAGE()
END CATCH

BEGIN TRY 
DECLARE @A INT = 4, @B INT = 0, @RESULT INT ;
SET @RESULT = @A / @B;
END TRY
BEGIN CATCH
DECLARE @ERMESSAGE NVARCHAR(2048),
        @ERSEVERITY INT,
		@ERSTATE INT
SELECT @ERMESSAGE = ERROR_MESSAGE(),
       @ERSEVERITY = ERROR_SEVERITY(),
	   @ERSTATE = ERROR_STATE()
RAISERROR(@ERMESSAGE, @ERSEVERITY, @ERSTATE )
END CATCH
